"""
Project Euler Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def SumEvenFibonacci(i,j,max):
    x = i * ((i%2)^1)
    if (j < max):
        return x + SumEvenFibonacci(j,i+j,max)
    else:
        return x

print(SumEvenFibonacci(1,2,4000000))